name: Publish to PyPI

on:
  push:
    tags:
      - '*'

concurrency:
  group: build-pypi-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/khelpers
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    # retrieve your distributions here

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1