name: Publish to Test PyPI

on:
  push:
    branches: [ dev ]
    paths: ['dist/**']

concurrency:
  group: build-pypi-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: test-pypi
      url: https://test.pypi.org/p/khelpers
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    # retrieve your distributions here

    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        packages-dir: dist/